language: node_js
node_js:
  - "10.16.3"

sudo: true
dist: bionic

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - npm install
  - npm i --prefix=./node_modules/protractor --save webdriver-manager@latest
  - npx webdriver-manager update --versions.chrome=`google-chrome --product-version`
  - cp src/environments/environment.prod.ts src/environments/environment.ts
  - cp e2e/travis.protractor.conf.js e2e/protractor.conf.js

script:
  - google-chrome --version
  - ng e2e --webdriver-update=false
  - ng test --watch=false --browsers=ChromeHeadless
